spring.application.name=streamflix-backend
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=streamflix_db;encrypt=true;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=Password123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

app.jwt.secret=change-this-development-secret-change-this-development-secret
app.jwt.expiration-ms=86400000
app.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:*,http://127.0.0.1:*}
tmdb.api.key=f159bc651073d7ad1bf1ea0b2bacba82
tmdb.base-url=https://api.themoviedb.org/3

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO
logging.level.com.streamflix=DEBUG
spring.jackson.serialization.indent-output=true
